### ISSUE TITLE
Pipe simulator output to console

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-gradle-plugin#12]
Currently the plugin doesn't pipe the simulator output to the console when launched via the launchIPhoneSimulator etc. task. Since debugging is currently not supported in RoboVM, it'd be very nice to at least see the console log.

Thanks for your work on this, we libgdx folks are super happy users :)

**Comment by ntherning** [comment]
Is this still a problem? We did have some problems with ios-sim at some point when Apple did some changes in how stdout/stderr are handled.

**Comment by abram** [comment]
gradle -debug seems to be required to see logged output in the console when running in the simulator. (For some reason gradle -i is enough to do the trick when running on-device.)

**Comment by badlogic** [comment]
Closing in favor of #44
