### ISSUE TITLE
Revoked certificates in the keychain break the whole build

### ISSUE THREAD

**Issue by akumlehn** [robovm/robovm-gradle-plugin#20]
Our build broke completely due to a revoked certificate in the keychain. Whenever the plugin encounters a revoked certificate, it skips all further attemps and throws the usual error "No signing identity found..." without trying further available codesigning certificates (this was quite misleading).

We fixed our local build by removing the revoked stuff. Nevertheless, it would be nice to skip revoked certificates or, at least, to provide a fitting message.

**Comment by ntherning** [comment]
This should have been fixed after the fix for robovm/robovm#392. Closing this now.
