### ISSUE TITLE
Plugin doesn't seem to use parallel compilation

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-gradle-plugin#25]
My 8 cores are pretty much idle when building with the plugin. Given the latest API additions which pull in a lot more classes for a barebones app, this has a very bad impact on overall compile times.

**Comment by ntherning** [comment]
Is this something you're still seeing? On my system all cores are working hard when building using Gradle.

**Comment by ntherning** [comment]
Haven't heard this from anyone else and haven't seen it myself.
