### ISSUE TITLE
Gradle says "Failed to launch IOS Simulator", although the application is actually launched

### ISSUE THREAD

**Issue by magicgoose** [robovm/robovm-gradle-plugin#39]
I'm trying to build&run HelloWorld sample from here: https://github.com/robovm/robovm-samples/tree/master/HelloWorld

I did run `gradle build` and then `gradle :HelloWorld:launchIPhoneSimulator`.

This is the output I got:

	:HelloWorld:launchIPhoneSimulator FAILED

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':HelloWorld:launchIPhoneSimulator'.
	> Failed to launch IOS Simulator

Although it did launch the application in the simulator (which was already launched).

The error doesn't occur every time — after I tried again, everything worked.

**Comment by ntherning** [comment]
Please run gradle with `--debug` and `--stacktrace` and post the output somewhere (not in this issue though since it will be huge).

**Comment by magicgoose** [comment]
Just tried this, but couldn't reproduce the issue anymore. So, I guess, I should close it for now. Thank you for the attention. :smile:
