### ISSUE TITLE
Suggestion: Add a "Clean Cache" option on the menu

### ISSUE THREAD

**Issue by rotter** [robovm/robovm-gradle-plugin#40]
Add a menu option to clean the .robovm folder, since deleting that folder is a common 1st step when a weird problem happens.

**Comment by badlogic** [comment]
This should probably go to the robovm-eclipse and robovm-idea issue
trackers. Could you close this issue and send issues to the othet two
trackers? Thanks!

**Comment by rotter** [comment]
Ops, sorry. Will do it now.
