### ISSUE TITLE
Gradle 2.5 (with libgdx)

### ISSUE THREAD

**Issue by mars3142** [robovm/robovm-gradle-plugin#46]
After changing from Gradle 2.4 to 2.5 I received the error

    > Failed to apply plugin [id 'robovm']
        > Could not generate a proxy class for class org.robovm.gradle.tasks.IPhoneSimulatorTask.

Changing back to 2.4 and everything works fine.

Tested with 

    org.robovm:robovm-gradle-plugin:1.5.0

**Comment by badlogic** [comment]
Thanks for reporting, this should be fixed in the next nightly build. To use the SNAPSHOT build of RoboVM, modify your `build.gradle` to use the RoboVM Gradle plugin SNAPSHOT:

```groovy
buildscript {
    repositories {
        mavenCentral()        
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    }
    dependencies {
        classpath 'org.robovm:robovm-gradle-plugin:1.5.1-SNAPSHOT'
    }
}
```
