### ISSUE TITLE
Move simulator properties from project to task scope

### ISSUE THREAD

**Issue by rivancic** [robovm/robovm-gradle-plugin#50]
It would be way easier to use if the IPadSimulatorTask allows setting properties directly on the task instead of using Project Properties here. If this is possible.

Taken from SO [Set the project properties in subclassed gradle task] (http://stackoverflow.com/questions/31898162/set-the-project-properties-in-subclassed-gradle-task/31899602?noredirect=1#comment51749381_31899602)

**Comment by badlogic** [comment]
You can overwrite and set properties as arguments to the Gradle command. Simply use `-PpropertyName=propertyValue` when invoking Gradle.
